services:
- type: web
  name: bigcommerce-sample-app
  env: node
  startCommand: npm install && AUTH_CALLBACK="${RENDER_EXTERNAL_URL}/api/auth" npm run start
  buildCommand: npm install && npm run build
  envVars:
  # The client id of your app, provided by the BigCommerce developer portal.
  # https://developer.bigcommerce.com/api-docs/apps/quick-start#register-a-draft-app
  - key: CLIENT_ID
    sync: false
  # The client secret of your app, provided by the BigCommerce developer portal.
  - key: CLIENT_SECRET
    sync: false
  # The fully qualified authentication endpoint provided by this app. Replace the app name with the app name chosen above.
  - key: AUTH_CALLBACK
    sync: false
  # Key the app will use for signing JWT. Use a 32+ random character secret
  - key: JWT_KEY
    generateValue: true
  - key: DB_TYPE
    value: mysql
  - fromGroup: mysql
  - key: MYSQL_HOST
    fromService:
      name: mysql
      type: pserv
      property: host

- type: pserv
  name: mysql
  plan: standard
  env: docker
  repo: https://github.com/render-examples/mysql
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 10
  envVars:
  - fromGroup: mysql

envVarGroups:
- name: mysql
  envVars:
  - key: MYSQL_DATABASE
    value: mysql
  - key: MYSQL_USER
    value: mysql
  - key: MYSQL_USERNAME
    value: mysql
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true
